// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/calendar" | "/admin/campus-map" | "/admin/directory" | "/admin/escalations" | "/admin/faqs" | "/admin/knowledge-base" | "/admin/notifications" | "/admin/post" | "/admin/resources" | "/admin/rules" | "/admin/services" | "/admin/settings" | "/admin/system-logs" | "/admin/users" | "/admin/whatsapp" | "/announcements" | "/calendar" | "/campus-map" | "/chat" | "/complete-profile" | "/dashboard" | "/dean" | "/dean/analytics" | "/dean/campus-map" | "/dean/notifications" | "/dean/settings" | "/documents" | "/flashcards" | "/goals" | "/lecturer" | "/lecturer/analytics" | "/lecturer/announcements" | "/lecturer/cohorts" | "/lecturer/escalations" | "/lecturer/knowledge-base" | "/lecturer/notifications" | "/lecturer/resources" | "/lecturer/schedules" | "/lecturer/settings" | "/login" | "/notes" | "/notifications" | "/planner" | "/settings" | "/signup"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/calendar": {}
  "/admin/campus-map": {}
  "/admin/directory": {}
  "/admin/escalations": {}
  "/admin/faqs": {}
  "/admin/knowledge-base": {}
  "/admin/notifications": {}
  "/admin/post": {}
  "/admin/resources": {}
  "/admin/rules": {}
  "/admin/services": {}
  "/admin/settings": {}
  "/admin/system-logs": {}
  "/admin/users": {}
  "/admin/whatsapp": {}
  "/announcements": {}
  "/calendar": {}
  "/campus-map": {}
  "/chat": {}
  "/complete-profile": {}
  "/dashboard": {}
  "/dean": {}
  "/dean/analytics": {}
  "/dean/campus-map": {}
  "/dean/notifications": {}
  "/dean/settings": {}
  "/documents": {}
  "/flashcards": {}
  "/goals": {}
  "/lecturer": {}
  "/lecturer/analytics": {}
  "/lecturer/announcements": {}
  "/lecturer/cohorts": {}
  "/lecturer/escalations": {}
  "/lecturer/knowledge-base": {}
  "/lecturer/notifications": {}
  "/lecturer/resources": {}
  "/lecturer/schedules": {}
  "/lecturer/settings": {}
  "/login": {}
  "/notes": {}
  "/notifications": {}
  "/planner": {}
  "/settings": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
