// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calendar">> = Specific
  const handler = {} as typeof import("../../app/admin/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/campus-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/campus-map">> = Specific
  const handler = {} as typeof import("../../app/admin/campus-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/directory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/directory">> = Specific
  const handler = {} as typeof import("../../app/admin/directory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/escalations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/escalations">> = Specific
  const handler = {} as typeof import("../../app/admin/escalations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faqs">> = Specific
  const handler = {} as typeof import("../../app/admin/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/knowledge-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/knowledge-base">> = Specific
  const handler = {} as typeof import("../../app/admin/knowledge-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/notifications">> = Specific
  const handler = {} as typeof import("../../app/admin/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/post/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/post">> = Specific
  const handler = {} as typeof import("../../app/admin/post/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/resources">> = Specific
  const handler = {} as typeof import("../../app/admin/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/rules">> = Specific
  const handler = {} as typeof import("../../app/admin/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/services">> = Specific
  const handler = {} as typeof import("../../app/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/system-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/system-logs">> = Specific
  const handler = {} as typeof import("../../app/admin/system-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp">> = Specific
  const handler = {} as typeof import("../../app/admin/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../app/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/campus-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campus-map">> = Specific
  const handler = {} as typeof import("../../app/campus-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/complete-profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/complete-profile">> = Specific
  const handler = {} as typeof import("../../app/complete-profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean/analytics">> = Specific
  const handler = {} as typeof import("../../app/dean/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/campus-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean/campus-map">> = Specific
  const handler = {} as typeof import("../../app/dean/campus-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean/notifications">> = Specific
  const handler = {} as typeof import("../../app/dean/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean">> = Specific
  const handler = {} as typeof import("../../app/dean/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dean/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dean/settings">> = Specific
  const handler = {} as typeof import("../../app/dean/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../app/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/flashcards/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flashcards">> = Specific
  const handler = {} as typeof import("../../app/flashcards/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/analytics">> = Specific
  const handler = {} as typeof import("../../app/lecturer/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/announcements">> = Specific
  const handler = {} as typeof import("../../app/lecturer/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/cohorts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/cohorts">> = Specific
  const handler = {} as typeof import("../../app/lecturer/cohorts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/escalations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/escalations">> = Specific
  const handler = {} as typeof import("../../app/lecturer/escalations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/knowledge-base/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/knowledge-base">> = Specific
  const handler = {} as typeof import("../../app/lecturer/knowledge-base/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/notifications">> = Specific
  const handler = {} as typeof import("../../app/lecturer/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer">> = Specific
  const handler = {} as typeof import("../../app/lecturer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/resources">> = Specific
  const handler = {} as typeof import("../../app/lecturer/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/schedules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/schedules">> = Specific
  const handler = {} as typeof import("../../app/lecturer/schedules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lecturer/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lecturer/settings">> = Specific
  const handler = {} as typeof import("../../app/lecturer/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notes">> = Specific
  const handler = {} as typeof import("../../app/notes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/planner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/planner">> = Specific
  const handler = {} as typeof import("../../app/planner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../app/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
